shared:
  image: bitnami/git:latest
  steps:
    - test: echo 'test'

jobs:
  A-success:
    requires: [ ~commit, ~pr ]
    annotations:
      screwdriver.cd/displayName: "✅ A [ ~commit, ~pr ]"

  A-failure:
    requires: [ ~commit, ~pr ]
    annotations:
      screwdriver.cd/displayName: "❌ A [ ~commit, ~pr ]"
    steps: &failure_steps
      - meta: |
          if [ "$(meta get restart)" != '1' ]; then
            meta set restart '1'
            exit 1
          fi
