shared:
    image: node:20
jobs:
    first:
        requires: [~pr, ~commit]
        steps: 
            - echo: |
                for i in {1..10}
                do
                  echo "${i}"
                  sleep "${i}"
                done
