shared:
  image: bitnami/git:latest
  steps:
    - test: echo 'test'

jobs:
  A-success:
    requires: [ sd@1:A-success ]
    annotations:
      screwdriver.cd/displayName: "✅ A [ sd@1:A○ ]"

  A-not-run:
    requires: [ sd@1:A-failure ]
    annotations:
      screwdriver.cd/displayName: "🔳 A [ sd@1:A○ ]"
    steps: &failure_steps
      - meta: |
          if [ "$(meta get restart)" != '1' ]; then
            meta set restart '1'
            exit 1
          fi

  B-success:
    requires: [ sd@1:A-success ]
    annotations:
      screwdriver.cd/displayName: "✅ B [ sd@1:A○ ]"

  B-not-run:
    requires: [ sd@1:A-failure ]
    annotations:
      screwdriver.cd/displayName: "🔳 B [ sd@1:A× ]"
    steps: *failure_steps

  tilde-A-success:
    requires: [ ~sd@1:A-success ]
    annotations:
      screwdriver.cd/displayName: "✅ A [ ~sd@1:A○ ]"

  tilde-A-not-run:
    requires: [ ~sd@1:A-failure ]
    annotations:
      screwdriver.cd/displayName: "🔳 A [ ~sd@1:A× ]"
    steps: *failure_steps

  tilde-B-success:
    requires: [ ~sd@1:A-success ]
    annotations:
      screwdriver.cd/displayName: "✅ B [ ~sd@1:A○ ]"

  tilde-B-not-run:
    requires: [ ~sd@1:A-failure ]
    annotations:
      screwdriver.cd/displayName: "🔳 B [ ~sd@1:A× ]"
    steps: *failure_steps