# ----------------------------------------------------------------------------------------------------------------------
#
#   Shared
#
# ----------------------------------------------------------------------------------------------------------------------
shared:
  image: bitnami/git:latest
  annotations:
    failure:
      steps: &failure_steps
        - failure: exit 1
  steps:
    - test: echo 'test'

# ----------------------------------------------------------------------------------------------------------------------
#
#   Jobs
#
# ----------------------------------------------------------------------------------------------------------------------
jobs:
  hub:
    requires: [ ~commit, ~pr ]
  a:
    requires: [ ~hub ]
    steps: *failure_steps
  b:
    requires: [ ~hub ]
    steps: *failure_steps
  target:
    requires: [ ~a, ~b ]
