# ----------------------------------------------------------------------------------------------------------------------
#
#   Shared
#
# ----------------------------------------------------------------------------------------------------------------------
shared:
  image: bitnami/git:latest
  annotations:
    a:
      steps: &a
        - metadata: |
            if [ "$(meta get parameters.success_a.value != "true" )" ]; then
              exit 1
            fi
    b:
      steps: &b
        - metadata: |
            if [ "$(meta get parameters.success_b.value != "true" )" ]; then
              exit 1
            fi
  steps:
    - test: echo 'test'

parameters:
  success_a: [" ", true", "false"]
  success_b: [" ", "true", "false"]

# ----------------------------------------------------------------------------------------------------------------------
#
#   Jobs
#
# ----------------------------------------------------------------------------------------------------------------------
jobs:
  hub_a:
    requires: [ ~sd@1:hub ]
  hub_b:
    requires: [ ~sd@1:hub ]
  a-success:
    requires: [ ~hub_a ]
    steps:
      - metadata: |
          if [ "$(meta get parameters.success_a.value == "false" )" ]; then
            exit 1
          fi
  a-failure:
    requires: [ ~hub_a ]
    steps:
      - metadata: |
          if [ "$(meta get parameters.success_a.value != "true" )" ]; then
            exit 1
          fi
  b-success:
    requires: [ ~hub_b ]
    steps:
      - metadata: |
          if [ "$(meta get parameters.success_b.value == "false" )" ]; then
            exit 1
          fi
  b-failure:
    requires: [ ~hub_b ]
    steps:
      - metadata: |
          if [ "$(meta get parameters.success_b.value != "true" )" ]; then
            exit 1
          fi
  target:
    requires: [ sd@2:a, sd@2:b ]
