shared:
  image: bitnami/git:latest
  steps:
    - test: echo 'test'

jobs:
  A-success:
    requires: [ sd@1:A-success ]
    annotations:
      screwdriver.cd/displayName: "✅ A [ sd@1:A○ ]"

  B-success:
    requires: [ sd@1:B-success ]
    annotations:
      screwdriver.cd/displayName: "✅ B [ sd@1:B○ ]"

  A-not-run:
    requires: [ sd@1:A-failure ]
    annotations:
      screwdriver.cd/displayName: "❌ A [ sd@1:A○ ]"

  B-not-run:
    requires: [ sd@1:B-failure ]
    annotations:
      screwdriver.cd/displayName: "❌ B [ sd@1:B□ ]"

  tilde-A-success:
    requires: [ sd@1:A-success ]
    annotations:
      screwdriver.cd/displayName: "✅ ~A [ ~sd@1A○ ]"

  tilde-B-success:
    requires: [ sd@1:B-success ]
    annotations:
      screwdriver.cd/displayName: "✅ ~B [ ~sd@1B○ ]"

  tilde-A-not-run:
    requires: [ sd@1:A-failure ]
    annotations:
      screwdriver.cd/displayName: "❌ ~A [ ~sd@1A□ ]"

  tilde-B-not-run:
    requires: [ sd@1:B-failure ]
    annotations:
      screwdriver.cd/displayName: "❌ ~B [ ~sd@1B□ ]"
