# ----------------------------------------------------------------------------------------------------------------------
#
#   Shared
#
# ----------------------------------------------------------------------------------------------------------------------
shared:
  image: bitnami/git:latest
  steps:
    - test: echo 'test'

# ----------------------------------------------------------------------------------------------------------------------
#
#   Jobs
#
# ----------------------------------------------------------------------------------------------------------------------
jobs:
  hub:
    requires: [ ~commit, ~pr ]
  target1:
    requires: [ sd@2:a-success, sd@2:b-success ]
    annotations:
      screwdriver.cd/displayName: "[ sd@2:a✅, sd@2:b✅ ]"
  target2:
    requires: [ sd@2:a-success, sd@2:b-failure ]
    annotations:
      screwdriver.cd/displayName: "[ sd@2:a✅, sd@2:b❌ ]"
  target3:
    requires: [ sd@2:a-failure, sd@2:b-success ]
    annotations:
      screwdriver.cd/displayName: "[ sd@2:a❌, sd@2:b✅ ]"
  target4:
    requires: [ sd@2:a-failure, sd@2:b-failure ]
    annotations:
      screwdriver.cd/displayName: "[ sd@2:a❌, sd@2:b❌ ]"