# ----------------------------------------------------------------------------------------------------------------------
#
#   Shared
#
# ----------------------------------------------------------------------------------------------------------------------
shared:
  image: bitnami/git:latest
  steps:
    - test: echo 'test'

parameters:
  restart_all: ["false", "true"]

# ----------------------------------------------------------------------------------------------------------------------
#
#   Jobs
#
# ----------------------------------------------------------------------------------------------------------------------
jobs:
  hub:
    requires: [ ~commit, ~pr ]
  a:
    requires: [ ~hub ]
  b:
    requires: [ ~hub ]
  c:
    requires: [ ~hub ]
  target:
    requires: [ ~a, a ]
