shared:
  image: bitnami/git:latest
  steps:
    - test: echo 'test'

jobs:
  A-success:
    requires: [ ~commit, ~pr ]
    annotations:
      screwdriver.cd/displayName: "✅ A [ ~commit, ~pr ]"

  A-failure:
    requires: [ ~commit, ~pr ]
    annotations:
      screwdriver.cd/displayName: "❌ A [ ~commit, ~pr ]"
    steps: &failure-steps
      - meta: |
          if [ "$(meta get restart)" -ne '1' ]; then
            meta set restart '1'
            exit 1
          fi

  B-success:
    requires: [ ~commit, ~pr ]
    annotations:
      screwdriver.cd/displayName: "✅ B [ ~commit, ~pr ]"

  B-failure:
    requires: [ ~commit, ~pr ]
    annotations:
      screwdriver.cd/displayName: "❌ B× [ ~commit, ~pr ]"
    steps: *failure-steps

  A-success-and-A-success:
    requires: [ A-success, sd@2:A-success ]
    annotations:
      screwdriver.cd/displayName: "✅ AA [ A○, sd@2A○ ]"

  A-success-and-A-failure:
    requires: [ A-failure, sd@2:A-success ]
    annotations:
      screwdriver.cd/displayName: "↻ AA [ A×, sd@2A○ ]"

  A-failure-and-A-success:
    requires: [ A-success, sd@2:A-failure ]
    annotations:
      screwdriver.cd/displayName: "↻ AA [ A○, sd@2A× ]"

  A-failure-and-A-failure:
    requires: [ A-failure, sd@2:A-failure]
    annotations:
      screwdriver.cd/displayName: "↻ AA [ A×, sd@2A× ]"

  A-success-and-B-success:
    requires: [ sd@2:A-success, sd@2:B-success ]
    annotations:
      screwdriver.cd/displayName: "✅ AB [ sd@2A○, sd@2B○ ]"

  A-success-and-B-failure:
    requires: [ sd@2:A-success, sd@2:B-failure ]
    annotations:
      screwdriver.cd/displayName: "↻ AB [ sd@2A○, sd@2B× ]"

  A-failure-and-B-success:
    requires: [ sd@2:A-failure, sd@2:B-success ]
    annotations:
      screwdriver.cd/displayName: "↻ AB [ sd@2A×, sd@2B○ ]"

  A-failure-and-B-failure:
    requires: [ sd@2:A-failure, sd@2:B-failure ]
    annotations:
      screwdriver.cd/displayName: "↻ AB [ sd@2A×, sd@2B× ]"

  tilde-A-success-tilde-A-success:
    requires: [ A-success, sd@2:A-success ]
    annotations:
      screwdriver.cd/displayName: "✅ AA [ ~A○, ~sd@2A○ ]"

  tilde-A-failure-tilde-A-failure:
    requires: [ A-failure, sd@2:A-failure ]
    annotations:
      screwdriver.cd/displayName: "↻ AA [ ~A×, ~sd@2A× ]"

  tilde-A-success-tilde-B-success:
    requires: [ sd@2:A-success, sd@2:B-success ]
    annotations:
      screwdriver.cd/displayName: "✅ AB [ ~sd@2A○, ~sd@2B○ ]"

  tilde-A-failure-tilde-B-success:
    requires: [ sd@2:A-failure, sd@2:B-success ]
    annotations:
      screwdriver.cd/displayName: "✅ AB [ ~sd@2A×, ~sd@2B○ ]"

  tilde-A-success-tilde-B-failure:
    requires: [ sd@2:A-success, sd@2:B-failure ]
    annotations:
      screwdriver.cd/displayName: "✅ AB [ ~sd@2A○, ~sd@2B× ]"

  tilde-A-failure-tilde-B-failure:
    requires: [ sd@2:A-failure, sd@2:B-failure ]
    annotations:
      screwdriver.cd/displayName: "↻ AB [ ~sd@2A×, ~sd@2B× ]"
