# ----------------------------------------------------------------------------------------------------------------------
#
#   Shared
#
# ----------------------------------------------------------------------------------------------------------------------
shared:
  image: bitnami/git:latest
  steps:
    - test: echo 'test'

# ----------------------------------------------------------------------------------------------------------------------
#
#   Jobs
#
# ----------------------------------------------------------------------------------------------------------------------
jobs:
  hub:
    requires: [ ~commit, ~pr ]
  a:
    requires: [ ~hub ]
  target1:
    requires: [ a ]
  target2:
    requires: [ a ]
