shared:
  image: node:20
  steps:
    - test: echo 'test'


jobs:
  A-success:
    requires: [ sd@1:A-success ]
    annotations:
      screwdriver.cd/displayName: "[ A○ ]"

  B-success:
    requires: [ sd@1:A-success ]
    annotations:
      screwdriver.cd/displayName: "[ B○ ]"

  A-failure:
    requires: [ sd@1:A-failure ]
    annotations:
      screwdriver.cd/displayName: "[ A× ]"

  B-failure:
    requires: [ sd@1:A-failure ]
    annotations:
      screwdriver.cd/displayName: "[ B× ]"

  tilde-A-success:
    requires: [ ~sd@1:A-success ]
    annotations:
      screwdriver.cd/displayName: "[ ~A○ ]"

  tilde-B-success:
    requires: [ ~sd@1:A-success ]
    annotations:
      screwdriver.cd/displayName: "[ ~B○ ]"

  tilde-A-failure:
    requires: [ ~sd@1:A-failure ]
    annotations:
      screwdriver.cd/displayName: "[ ~A× ]"

  tilde-B-failure:
    requires: [ ~sd@1:A-failure ]
    annotations:
      screwdriver.cd/displayName: "[ ~B× ]"
